### ISSUE TITLE
I keep getting this KeyError: <flask_pymemcache.FlaskPyMemcache object at 0x7ff2e6bb7d10>

### ISSUE THREAD

**Issue by nupiter** [KLab/Flask-PyMemcache#2]
I have followed every step for configuration (not like there is a lot), but I keep getting this same error every single time:
```
Traceback (most recent call last):
  File "/home/arturo/PycharmProjects/virtualenvs/py37_lobby_api/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/arturo/PycharmProjects/virtualenvs/py37_lobby_api/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/arturo/PycharmProjects/virtualenvs/py37_lobby_api/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/arturo/PycharmProjects/virtualenvs/py37_lobby_api/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/arturo/PycharmProjects/virtualenvs/py37_lobby_api/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/arturo/PycharmProjects/virtualenvs/py37_lobby_api/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/arturo/PycharmProjects/sar-lobby-api/lobby/api/reservations/endpoints.py", line 18, in get_reservation
    reserva = cache.client.get(url_code)
  File "/home/arturo/PycharmProjects/virtualenvs/py37_lobby_api/lib/python3.7/site-packages/flask_pymemcache.py", line 100, in client
    return flask.current_app.extensions['pymemcache'][self]
KeyError: <flask_pymemcache.FlaskPyMemcache object at 0x7ff2e6bb7d10>

```

**Comment by nupiter** [comment]
This is part of my run.py file:
```
app = Flask(__name__)
app.config.from_pyfile('config.py')

cache = FlaskPyMemcache()
cache.init_app(app)

```

**Comment by methane** [comment]
I can not reproduce. You may using multiple apps or have misconfiguration.
